// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM0ZjD8V-HFNdppmp1y1SCmSLxUrsVsrs',
    appId: '1:697445270339:web:16c313fada9a94e57d25f6',
    messagingSenderId: '697445270339',
    projectId: 'tremor-32fd3',
    authDomain: 'tremor-32fd3.firebaseapp.com',
    databaseURL: 'https://tremor-32fd3-default-rtdb.firebaseio.com',
    storageBucket: 'tremor-32fd3.appspot.com',
    measurementId: 'G-JHWG5Y0KW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo6yQgLMrfDQFZ2AKVaUagYIngeTXVNBI',
    appId: '1:697445270339:android:7626e41c273353277d25f6',
    messagingSenderId: '697445270339',
    projectId: 'tremor-32fd3',
    databaseURL: 'https://tremor-32fd3-default-rtdb.firebaseio.com',
    storageBucket: 'tremor-32fd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrEfB0ojMAlTQQ-5IiH6vZOo_bfJW1LsU',
    appId: '1:697445270339:ios:34f63048e72339127d25f6',
    messagingSenderId: '697445270339',
    projectId: 'tremor-32fd3',
    databaseURL: 'https://tremor-32fd3-default-rtdb.firebaseio.com',
    storageBucket: 'tremor-32fd3.appspot.com',
    iosClientId: '697445270339-eqa5223grov7napd0sf56frcf2vi2n3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.tremor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrEfB0ojMAlTQQ-5IiH6vZOo_bfJW1LsU',
    appId: '1:697445270339:ios:4b2ddefa0b9f5a1e7d25f6',
    messagingSenderId: '697445270339',
    projectId: 'tremor-32fd3',
    databaseURL: 'https://tremor-32fd3-default-rtdb.firebaseio.com',
    storageBucket: 'tremor-32fd3.appspot.com',
    iosClientId: '697445270339-079sedtrn8kn5h68kqdnddi72oui60vp.apps.googleusercontent.com',
    iosBundleId: 'com.example.tremor.RunnerTests',
  );
}
